forge 'forge.puppetlabs.com'

# Forge Modules
mod 'puppetlabs/ntp', '4.1.2'
mod 'puppetlabs/stdlib', '4.10.0'

mod 'openstack-keystone', '6.1.0'
mod 'openstack-heat', '6.1.0'
mod 'openstack-nova', '6.1.0'
mod 'openstack-neutron', '6.1.0'
mod 'openstack-cinder', '6.1.0'
mod 'openstack-glance', '6.1.0'
mod 'openstack-openstacklib', '6.1.0'
mod 'openstack-vswitch' '2.1.0'
mod 'dprince-qpid', '1.0.3'
mod 'duritong-sysctl', '0.0.11'

mod 'puppetlabs/apache', '1.6.0'
mod 'puppetlabs/apt', '2.1.1'
mod 'puppetlabs/concat', '1.2.4'
mod 'puppetlabs/firewall', '1.7.0'
mod 'puppetlabs/gcc', '0.3.0'
mod 'puppetlabs/git', '0.4.0'
mod 'puppetlabs/haproxy', '1.3.0'
mod 'puppetlabs/inifile', '1.4.1'
mod 'puppetlabs/ntp', '4.1.0'
mod 'puppetlabs/passenger', '0.4.1'
mod 'puppetlabs/pe_gem', '0.1.1'
mod 'puppetlabs/postgresql', '4.5.0'
mod 'puppetlabs/rabbitmq', '5.2.3'
mod 'puppetlabs/ruby', '0.4.0'
mod 'puppetlabs/stdlib', '4.7.0'
mod 'puppetlabs/vcsrepo', '1.3.1'
mod 'croddy/make', '0.0.5'
mod 'fiddyspence/sysctl', '1.1.0'
mod 'gentoo/portage', '2.3.0'
mod 'ghoneycutt/common', '1.3.0'
mod 'hunner/hiera', '1.3.1'
mod 'jfryman/nginx', '0.2.7'
mod 'nanliu/staging', '1.0.3'
mod 'ripienaar/module_data', '0.0.3'
mod 'saz/sudo', '3.1.0'
mod 'zack/r10k', '2.8.3'
